name: Deploy Leptos PWA to GitHub Pages

on:
  push:
    branches:
      - main # 如果您的預設分支是 master，請改為 master

# 設定 GitHub Token 的權限以允許部署至 Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 避免重複觸發時覆蓋掉正在執行的任務
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Download and Install Trunk
        run: |
          wget -qO- https://github.com/trunk-rs/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- -C /usr/local/bin
          trunk --version

      - name: Build Project with Trunk
        run: |
          trunk build --release --public-url /leptos-pwa-github-pages-starter/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 打包輸出的目錄（預設為 dist）
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4